[workspace]
members = [
    "components/clarinet-cli",
    "components/clarinet-deployments",
    "components/clarinet-deno",
    "components/clarinet-files",
    "components/clarinet-utils",
    "components/clarity-lsp",
    "components/stacks-rpc-client",
    "components/stacks-devnet-js",
    "vendor/orchestra-types-rs",
    "vendor/orchestra-event-observer",
]
default-members = ["components/clarinet-cli", "vendor/orchestra-event-observer"]
