[package]
name = "clarity-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-types = "0.93.0"
chainhook_types = { package = "chainhook-types", path = "../chainhook-types-rs" }
clarinet_files =  { package = "clarinet-files", path = "../clarinet-files", default-features = false }
clarity_repl = { package = "clarity-repl", path = "../clarity-repl", default-features = false }
clarinet_deployments =  { package = "clarinet-deployments", path = "../clarinet-deployments", default-features = false }

# WASM
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }

[features]
default = ["cli"]
cli = ["clarinet_deployments/cli", "clarinet_deployments/cli", "clarity_repl/cli", "clarinet_files/cli"]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "clarinet_deployments/wasm", "clarity_repl/wasm", "clarinet_files/wasm"]

[lib]
name = "clarity_lsp"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false