[project]
name = "counter"
authors = []
description = ""
telemetry = false
cache_dir = "./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.counter]
path = "contracts/counter.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
