[package]
name = "hiro-system-kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.12"
tokio = { version = "=1.17.0", features = ["full"] }
ansi_term = "0.12.1"
atty = "0.2.14"
