[project]
name = "with-requirements"
authors = []
description = ""
telemetry = false

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[project.cache_location]
path = ".cache"

[contracts.nft-project]
path = "contracts/nft-project.clar"

[repl.analysis]
passes = []
