[package]
name = "stacks-rpc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
clarity_repl = { package = "clarity-repl", path = "../clarity-repl" }
clarinet_utils = { package = "clarinet-utils", path = "../clarinet-utils" }
clarity = { git = "https://github.com/stacks-network/stacks-blockchain.git", branch = "refactor/clarity-lib-merge" }
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
